### ISSUE TITLE
Adorei seus slides

### ISSUE THREAD

**Issue by lostdusty** [YujiYashima/Arthropoda#1]
Olá Pedro, sou a Rebecca e tenho um [site de estudos](https://estudos.princessmortix.link) [\(fonte\)](https://github.com/princessmortix/estudos-do-quarto), você se importaria se eu usar os slides deste repo no meu site de estudos?

**Comment by YujiYashima** [comment]
Olá, Rebecca. Claro, pode utilizar o meu slide sim. Dei uma olhada no seu site e achei ele incrível e muito fácil de acessar. Gostei do seu trabalho.
